items = [
    [
        2002064122,
        [["1"], ["2"], ["3"], ["4"], ["5"]],
        1,
        ["a"],
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        [0],
    ],
    [
        349363879,
        [["1"], ["2"], ["3"], ["4"], ["5"]],
        1,
        ["b"],
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        [0],
    ],
    [
        60418222,
        [["1"], ["2"], ["3"], ["4"], ["5"]],
        1,
        ["c"],
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        [0],
    ],
    [
        2132067054,
        [["1"], ["2"], ["3"], ["4"], ["5"]],
        1,
        ["d"],
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        [0],
    ],
    [
        1711132281,
        [["1"], ["2"], ["3"], ["4"], ["5"]],
        1,
        ["e"],
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        [0],
    ],
    [
        875492939,
        [["1"], ["2"], ["3"], ["4"], ["5"]],
        1,
        ["f"],
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        [0],
    ],
]


for item in items: 
    print(item)